Rwa 219
hmcts/wa-workflow-api pull request #102
Opened 2020-12-07 18:42 UTC by indvamshi

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RWA-219

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-12-08 09:38 UTC, iguannago approved these changes

2020-12-08 09:43 UTC, alexbaeza requested changes

2020-12-08 09:43 UTC, alexbaeza commented on src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskTest.java
> +                Object tasks = given()
If we only extract the id, this should be a String

2020-12-08 09:43 UTC, alexbaeza commented on src/functionalTest/java/uk/gov/hmcts/reform/waworkflowapi/controllers/CreateTaskTest.java
> +                ((List<Object>) tasks).forEach(taskId -> cleanUp(taskId, serviceAuthorizationToken));
or maybe a list of Strings

2020-12-09 18:51 UTC, BenNzewi commented on src/testUtils/java/uk/gov/hmcts/reform/waworkflowapi/SpringBootFunctionalBaseTest.java
> +            .post();
As part of clean up, can we check the state of the completed task? I.e. check that the task no longer exists after completing.

2020-12-11 13:18 UTC, alexbaeza approved these changes

2020-12-14 10:47 UTC, merged